### ISSUE TITLE
Homepage theme applied to wrong pages creating styling error

### ISSUE THREAD

**Issue by kamarenmccord** [aidanhorton/ecosia-darkmode-extensions#7] opened 2021-02-09 19:56 UTC
<h4>Issue keeps happening on first use then goes away after refresh.</h4>
<p>creates a really <strong>hard</strong> contrast </p>
>>using firefox

![Screenshot from 2021-02-09 13-49-06](https://user-images.githubusercontent.com/43706940/107419929-f6734c00-6add-11eb-9e6c-2b6ce1073230.png)

**Comment by aidanhorton** [comment] 2021-02-10 10:52
Thanks for reporting this - I've actually seen this one before too.

I have some ideas as to why it's happening, I'll look into this in the next few weeks.

ETA - 1-3 weeks.

**Comment by thundercrypt** [comment] 2021-03-04 07:14
> #### Issue keeps happening on first use then goes away after refresh.
> creates a really **hard** contrast
> 
> >>using firefox
> ![Screenshot from 2021-02-09 13-49-06](https://user-images.githubusercontent.com/43706940/107419929-f6734c00-6add-11eb-9e6c-2b6ce1073230.png)

Hi, I'm experiencing the same problem, even though I'm using Chrome (on Linux).

![image](https://user-images.githubusercontent.com/77282722/109925018-2f6e9d00-7ce7-11eb-82c2-b57d10148176.png)

**Comment by aidanhorton** [comment] 2021-03-04 10:09
Yeah looks like the same one is on Chrome too then - is this a constant issue, or fairly rare?

Either way I'll fix it soon - I have a few ideas on how to tackle this.
I see this a little more than I'd like to admit in FireFox.

**Comment by aidanhorton** [comment] 2021-03-04 10:10
Sorry the ETA above is slightly off, it'll likely be another 0-2 weeks until a fix is implemented - apologies, but I'll try my best to meet the lower part of that estimate.

**Comment by thundercrypt** [comment] 2021-03-06 07:29
It's working now...

**Comment by thundercrypt** [comment] 2021-03-06 07:29
> Yeah looks like the same one is on Chrome too then - is this a constant issue, or fairly rare?
> 
> Either way I'll fix it soon - I have a few ideas on how to tackle this.
> I see this a little more than I'd like to admit in FireFox.

It happened once, I tried reloading the page, it was still there.

**Comment by aidanhorton** [comment] 2021-03-08 14:31
Yeah it's intermittent - it usually goes away after reloading or typing in a new search term.

**Comment by aidanhorton** [comment] 2021-03-22 11:11
Struggling to reproduce this issue - I need to get a glimpse of the page source when this happens so I can see exactly where the style overrides are sitting. I can't fix this until I can repro it so apologies for the delay!

**Comment by thundercrypt** [comment] 2021-03-22 15:51
> Struggling to reproduce this issue - I need to get a glimpse of the page source when this happens so I can see exactly where the style overrides are sitting. I can't fix this until I can repro it so apologies for the delay!

That's alright, take your time 😃

**Comment by aidanhorton** [comment] 2021-03-25 10:30
I've finally managed to reproduce it once so I can see what the issue is - it will make it difficult for testing but I'll see what I can do in that avenue.
The issue is that for some reason, it's applying the home-page styling onto the search page, see below:
![image](https://user-images.githubusercontent.com/22588585/112458619-e2fe0680-8d54-11eb-9770-7db3303cccc0.png)

Whereas it should be:
![image](https://user-images.githubusercontent.com/22588585/112458753-09bc3d00-8d55-11eb-8c50-0340ef89eea2.png)

I'll investigate this further and hopefully get a fix.

**Comment by thundercrypt** [comment] 2021-03-25 11:14
Alright. Thanks :) 😄

**Comment by aidanhorton** [comment] 2021-03-25 11:32
I've whacked together a temporary fix for this, by simply adding the search page theme to the homepage style. Turns out they don't 'intersect' each other, so they can safely both be put together.
This is only a temporary fix, as this will still be an issue with the images, news and videos page - but you're much more likely to see this issue in the serach page.
Commit ID: https://github.com/aidanhorton/ecosia-darkmode-extensions/commit/b907b27c436e41bc83683997df4703932513bcd2

**Comment by aidanhorton** [comment] 2021-03-25 11:33
In the process of being uploaded to the extension store, should be available in the next few hours.

**Comment by thundercrypt** [comment] 2021-03-25 11:34
okay.

**Comment by aidanhorton** [comment] 2021-04-06 11:01
I've attempted some further fixes for this issue, see this commit: https://github.com/aidanhorton/ecosia-darkmode-extensions/commit/d531c518c3f572075bfaaa04e82e82bfa7f37c46

What I've basically done is instead of checking for the homepage like this:
www.ecosia.org/* (where * means that the URL can be anything after that point)

I've hard-coded it to:
www.ecosia.org
&
www.ecosia.org/?* (to account for localisation URLs)

Hopefully this should stop the homepage style overriding any other styles - but I cannot really test if this issue is fixed or not as I only see it incredibly rarely. There is a small chance that this fix has made it worse, but we'll see.
I'll close this issue once I get confirmation from people who see this issue consistently.

**Comment by aidanhorton** [comment] 2021-07-15 14:55
Looks like this may have been fixed - haven't seen it anymore myself and have had no further reports, so will close unless it's re-raised!

**Closed by aidanhorton** 2021-07-15 14:55 UTC
Labels: bug
